### ISSUE TITLE
I can't get this to work? 

### ISSUE THREAD

**Issue by deppemj** [CimConnor/CimatronAPIShellExample#1]
Have you gotten APIShell to run like this? I can't get it to run, any hints on what I might be doing wrong?

**Comment by CimCad** [comment]
Yes I have gotten API shell to run. The most common error i see is that people forget to register for com-interop and expose the assembly to Com. If you can provide a better description on the error i may be able to further assist you.

**Comment by deppemj** [comment]
I've cloned your repo, built it to Programs, registered via Register_API_Commands  and got "command was register." CimInfo in the Programs folder lists ClassLibrary1 as an assembly. When I have Cimatron open I can still build it without error so Cimatron just isn't grabbing the DLL for some reason although everything indicates that it is registered? I've had similar results moving my DLLs to other computers and get the same behavior. Any ideas? 

Thanks for posting this repo, I wish more people would post their Cimatron commands and code online!

**Comment by CimCad** [comment]
What version of Cimatron are you running, also sometimes ive had commands not show up in the toolbar or menu, Although they always should show up under View-> Customize -> Customize Toolbar-> (Search Command Name). So you can try to search it. If you cant find it still then I would assume your problem is with visual studios auto registry. I have a fix for it but I wont be available to post the code until at least the 27th.

**Comment by deppemj** [comment]
I finally got it to work! I've been trying to work with APIShell for a year and a half and cimatron told me to ignore it so I figured it wasn't functional but this is amazing. Thank you so much for your help, this is going to save me loads of time! As I said before, I think it's awesome you're posting code, I wish more people would do this so we can help each other work through the cimatron API. I'm still very interested in your auto registry fix and the issue it addresses. When you post that code, make sure you post it in the Cimatron reddit as well!

**Comment by CimCad** [comment]
The auto registry address the problem that occurs when you try to manually register the Dll on someone's computer without visual studio. This happens because Cimatron needs the codeBase for the dll so it has to be strong named.

**Comment by deppemj** [comment]
I don't know enough to understand that, is there a way to fix that or ensure it doesn't happen? The issues I was having sound incredibly similar to that so I am curious if you have a fix.

**Comment by CimCad** [comment]
Yes the simple way to fix it is inside of visual studio right click on your project then go to properties and signing, Then sign the assembly and build. After that you can open Command prompt as an administrator a run the command ("C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe" (Path To DLL)  /codebase /tlb ) and this will register the command properly. The program I've made you can select the icons you want and the dll and it will generate a setup exe which can be ran and will install the API to every version of Cimatron downloaded.

**Comment by deppemj** [comment]
Wow that worked! I've been struggling with that for like 8 months, you have been saving me thank you! Where is that registering program? I can't find it on your github but it sounds like you planned on sharing it!

**Comment by CimCad** [comment]
I haven't had the time to properly package it and work through some of the bug's. But when I do get around to it i fully plan to post it along with some of my own documentation on the cimatron api because the current is lacking.

**Comment by deppemj** [comment]
absolutely agree, I appreciate you posting this! I wish more people posted Cimatron code so we can all learn from it! I'm trying to get the cimatron reddit working but it's not going well ha

**Comment by CimCad** [comment]
Ill take a look at it I Didn't even realize there was one
